Updated so now we compose a hana::map instead of inherit from it.
njoy/constants pull request #9
Opened 2020-06-30 02:38 UTC by jlconlin

2020-07-07 03:33 UTC, whaeck requested changes

2020-07-07 03:33 UTC, whaeck commented on src/constants/CODATA2018/test/CODATA2018.test.cpp
> +  // checkMap( aliasMap );
why make a map and not test it?

2020-07-07 09:16 UTC, jlconlin commented on src/constants/CODATA2018/test/CODATA2018.test.cpp
> +  // checkMap( aliasMap );
Good catch! This was removed while things were not working well. It is now back in.

2020-07-10 18:23 UTC, jlconlin commented
This is ready to go whenever someone wants to approve it.

2020-07-14 00:17 UTC, whaeck approved these changes
I did not look at the actual numbers and units, since I assume they were already verified.

2020-07-14 14:33 UTC, merged